# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81ffae0a5742d02c1596642030d34683bc499ecf3d3f431b2c157b3f7a450b4b9539edb6f5b058ea286032e255ae45020187dff6ce7055596c65e9d7dae31dc5

test:
  secret_key_base: 31bb6e53a07551e0fda0cfd61c803451d470f88f0aa0e49b4872ec0012037a270b91f7b091eaa9f668fd9796b95c4d65f889e0d87c932e9e9dc9152fc34ef551

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
